Fix possible exception when calling `Engine.clear_translator_state(undo=True)`.
